---
title: "Finding Shooting Percentages for All of the Big Ten"
author: '@jonmichaelstroh'
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler")
```

```{r load libraries}
library(tidyverse)
library(dplyr)
library(gamezoneR)
```

```{r Big Ten Team Schedules}
wisconsin_schedule_2020 <-  gamezoneR::get_team_schedule("Wisconsin", season = "2020-21")
michigan_schedule_2020 <-  gamezoneR::get_team_schedule("Michigan", season = "2020-21")
purdue_schedule_2020 <-  gamezoneR::get_team_schedule("Purdue", season = "2020-21")
iowa_schedule_2020 <-  gamezoneR::get_team_schedule("Iowa", season = "2020-21")
illinois_schedule_2020 <-  gamezoneR::get_team_schedule("Illinois", season = "2020-21")
michiganst_schedule_2020 <-  gamezoneR::get_team_schedule("Michigan State", season = "2020-21")
ohiost_schedule_2020 <-  gamezoneR::get_team_schedule("Ohio State", season = "2020-21")
indiana_schedule_2020 <-  gamezoneR::get_team_schedule("Indiana", season = "2020-21")
maryland_schedule_2020 <-  gamezoneR::get_team_schedule("Maryland", season = "2020-21")
rutgers_schedule_2020 <-  gamezoneR::get_team_schedule("Rutgers", season = "2020-21")
minnesota_schedule_2020 <-  gamezoneR::get_team_schedule("Minnesota", season = "2020-21")
pennst_schedule_2020 <-  gamezoneR::get_team_schedule("Penn State", season = "2020-21")
nebraska_schedule_2020 <-  gamezoneR::get_team_schedule("Nebraska", season = "2020-21")
northwestern_schedule_2020 <-  gamezoneR::get_team_schedule("Northwestern", season = "2020-21")

big_ten_schedule <- multiFull <- merge(merge(merge(merge(merge(merge(merge(merge(merge(merge(merge(merge(merge(
  wisconsin_schedule_2020,
  michigan_schedule_2020, all = TRUE),
  purdue_schedule_2020, all = TRUE),
  iowa_schedule_2020, all = TRUE),
  illinois_schedule_2020, all = TRUE),
  michiganst_schedule_2020, all = TRUE),
  ohiost_schedule_2020, all = TRUE),
  indiana_schedule_2020, all = TRUE),
  maryland_schedule_2020, all = TRUE),
  rutgers_schedule_2020, all = TRUE),
  minnesota_schedule_2020, all = TRUE),
  pennst_schedule_2020, all = TRUE),
  nebraska_schedule_2020, all = TRUE),
  northwestern_schedule_2020, all = TRUE)
```

```{r Shot data for Big Ten}
big_ten_shot_data <- purrr::map_df(big_ten_schedule$game_id, 
                          gamezoneR::gamezone_cbb_pbp, sub_parse = F) %>% filter(!is.na(loc_x)) %>% filter(home == event_team)
```

```{r Check Quadrants}
big_ten_shot_data  <- big_ten_shot_data  %>% mutate(shot_quadrant = factor(if_else(loc_x >= 21 & loc_x <= 25 & ((loc_y - 5.25)^2 + (25 - loc_x)^2 <= 16), "Q1", if_else(loc_x > 25 & loc_x <= 29 & ((loc_y - 5.25)^2 + (loc_x - 25)^2 <= 16), "Q1", if_else(loc_x >= 19 & loc_x <= 31 & loc_y <= 19, "Q2", if_else(loc_x <= 12.5 & three_pt == TRUE, "Q5", if_else(loc_x > 12.5 & loc_x < 37.5 & three_pt == TRUE, "Q6", if_else(loc_x >= 37.5 & three_pt == TRUE, "Q7", if_else(loc_x <= 25, "Q3", if_else(loc_x > 25, "Q4", "NA"))))))))))
```

```{r Total by Quadrant}
big_ten_shot_quadrants <- table(big_ten_shot_data$shot_quadrant, big_ten_shot_data$shot_outcome)

big_ten_shot_quadrants
```

```{r Percentages by Quadrant}
big_ten_shot_quadrant_percentages_2020 <- as.data.frame.matrix(round(prop.table(big_ten_shot_quadrants, 1), digits = 5) * 100)

big_ten_shot_quadrant_percentages_2020 <- big_ten_shot_quadrant_percentages_2020 %>% mutate(Quadrant = 1:nrow(big_ten_shot_quadrant_percentages_2020)) %>% mutate(made = paste0(made,"%"))
```


```{r Total by Quadrant by Shooter}
big_ten_shot_quadrants_players <- as.data.frame.matrix(table(big_ten_shot_data$shooter, big_ten_shot_data$shot_quadrant))
```

#### Quadrant 1

```{r Shooting Percentages Q1}
big_ten_shot_data_quadrant1 <- big_ten_shot_data %>% filter(shot_quadrant == "Q1")

big_ten_shot_data_quadrant1_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant1$shooter, big_ten_shot_data_quadrant1$shot_outcome)) %>% filter(made + missed >= 15) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q1 Distribution}
ggplot(data = big_ten_shot_data_quadrant1_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant1_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```

#### Quadrant 2

```{r Shooting Percentages Q2}
big_ten_shot_data_quadrant2 <- big_ten_shot_data %>% filter(shot_quadrant == "Q2")

big_ten_shot_data_quadrant2_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant2$shooter, big_ten_shot_data_quadrant2$shot_outcome)) %>% filter(made + missed >= 5) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q2 Distribution}
ggplot(data = big_ten_shot_data_quadrant2_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant2_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```

#### Quadrant 3

```{r Shooting Percentages Q3}
big_ten_shot_data_quadrant3 <- big_ten_shot_data %>% filter(shot_quadrant == "Q3")

big_ten_shot_data_quadrant3_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant3$shooter, big_ten_shot_data_quadrant3$shot_outcome)) %>% filter(made + missed >= 5) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q3 Distribution}
ggplot(data = big_ten_shot_data_quadrant3_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant3_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```

#### Quadrant 4

```{r Shooting Percentages Q4}
big_ten_shot_data_quadrant4 <- big_ten_shot_data %>% filter(shot_quadrant == "Q4")

big_ten_shot_data_quadrant4_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant4$shooter, big_ten_shot_data_quadrant4$shot_outcome)) %>% filter(made + missed >= 5) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q4 Distribution}
ggplot(data = big_ten_shot_data_quadrant4_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant4_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```

#### Quadrant 5

```{r Shooting Percentages Q5}
big_ten_shot_data_quadrant5 <- big_ten_shot_data %>% filter(shot_quadrant == "Q5")

big_ten_shot_data_quadrant5_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant5$shooter, big_ten_shot_data_quadrant5$shot_outcome)) %>% filter(made + missed >= 5) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q5 Distribution}
ggplot(data = big_ten_shot_data_quadrant5_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant5_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```

#### Quadrant 6

```{r Shooting Percentages Q6}
big_ten_shot_data_quadrant6 <- big_ten_shot_data %>% filter(shot_quadrant == "Q6")

big_ten_shot_data_quadrant6_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant6$shooter, big_ten_shot_data_quadrant6$shot_outcome)) %>% filter(made + missed >= 5) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q6 Distribution}
ggplot(data = big_ten_shot_data_quadrant6_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant6_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```

#### Quadrant 7

```{r Shooting Percentages Q7}
big_ten_shot_data_quadrant7 <- big_ten_shot_data %>% filter(shot_quadrant == "Q7")

big_ten_shot_data_quadrant7_players <- as.data.frame.matrix(table(big_ten_shot_data_quadrant7$shooter, big_ten_shot_data_quadrant7$shot_outcome)) %>% filter(made + missed >= 5) %>% mutate(shooting_percent = (made/(made + missed)) * 100)
```

```{r Shooting Percentages Q6 Distribution}
ggplot(data = big_ten_shot_data_quadrant7_players, aes(x = shooting_percent)) + 
  geom_histogram()

round(quantile(big_ten_shot_data_quadrant7_players$shooting_percent, c(.2, .4, .6, .8)), digits = 3)
```


