---
title: "Mapping Collegiate Basketball Shot Charts Trial Run"
author: '@jonmichaelstroh'
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler")
```

```{r load libraries}
library(tidyverse)
library(dplyr)
library(gamezoneR)
library(extrafont)
```

```{r Wisconsin schedule}
wisconsin_schedule_2020 <-  gamezoneR::get_team_schedule("Wisconsin", season = "2020-21")
```

```{r Trice's shots}
trice_shots_2020 <- purrr::map_df(wisconsin_schedule_2020$game_id, 
                          gamezoneR::gamezone_cbb_pbp, sub_parse = F) %>% filter(shooter == "D'Mitrik Trice")
```

#### Determine Quadrant

```{r Check Quadrants}
trice_shots_2020 <- trice_shots_2020 %>% mutate(shot_quadrant = factor(if_else(loc_x >= 21 & loc_x <= 25 & ((loc_y - 5.25)^2 + (25 - loc_x)^2 <= 16), "Q1", if_else(loc_x > 25 & loc_x <= 29 & ((loc_y - 5.25)^2 + (loc_x - 25)^2 <= 16), "Q1", if_else(loc_x >= 19 & loc_x <= 31 & loc_y <= 19, "Q2", if_else(loc_x <= 12.5 & three_pt == TRUE, "Q5", if_else(loc_x > 12.5 & loc_x < 37.5 & three_pt == TRUE, "Q6", if_else(loc_x >= 37.5 & three_pt == TRUE, "Q7", if_else(loc_x <= 25, "Q3", if_else(loc_x > 25, "Q4", "NA"))))))))))
```

#### The Number of Shots for each Quadrant

```{r Total by Quadrant}
trice_shot_quadrants <- table(trice_shots_2020$shot_quadrant, trice_shots_2020$shot_outcome)

trice_shot_quadrants
```

```{r Percentages by Quadrant}
trice_quadrant_percentages <- as.data.frame.matrix(prop.table(trice_shot_quadrants, 1) * 100)

trice_quadrant_percentages <- trice_quadrant_percentages %>% mutate(Quadrant = 1:nrow(trice_quadrant_percentages))

trice_quadrant_percentages <- trice_quadrant_percentages %>% mutate(color = if_else(Quadrant == 1,if_else(made < 51.834, "#1a1aff", if_else(made < 59.603, "#0099ff", if_else(made < 63.179, "#737373", if_else(made < 70.857 , "#ff8080", "#ff0000")))), if_else(Quadrant == 2,if_else(made < 33.333, "#1a1aff", if_else(made < 41.504, "#0099ff", if_else(made < 45.758, "#737373", if_else(made < 52.891 , "#ff8080", "#ff0000")))), if_else(Quadrant == 3,if_else(made < 21.778, "#1a1aff", if_else(made < 33.333, "#0099ff", if_else(made < 40.000, "#737373", if_else(made < 54.545 , "#ff8080", "#ff0000")))), if_else(Quadrant == 4,if_else(made < 24.444, "#1a1aff", if_else(made < 34.846, "#0099ff", if_else(made < 43.492, "#737373", if_else(made < 53.186, "#ff8080", "#ff0000")))), if_else(Quadrant == 5,if_else(made < 23.754, "#1a1aff", if_else(made < 32.800, "#0099ff", if_else(made < 37.500, "#737373", if_else(made < 48.000, "#ff8080", "#ff0000")))), if_else(Quadrant == 6,if_else(made < 25.000, "#1a1aff", if_else(made < 31.139, "#0099ff", if_else(made < 37.368, "#737373", if_else(made < 47.680, "#ff8080", "#ff0000")))), if_else(Quadrant == 7,if_else(made < 22.063, "#1a1aff", if_else(made < 30.462, "#0099ff", if_else(made < 36.364, "#737373", if_else(made < 40.333 , "#ff8080", "#ff0000")))), "NA"))))))))



trice_quadrant_percentages <- trice_quadrant_percentages %>% mutate(made = round(made), digits = 0) %>% mutate(made = paste0(made,"%"))

trice_quadrant_percentages
```

```{r Randomize Close Shots}
set.seed(2)
trice_shots_2020_test <- trice_shots_2020 %>% mutate(loc_x = if_else(shot_desc == "Layup Shot" & play_id < 250, loc_x + runif(1, -2, 2), if_else(shot_desc == "Layup Shot" & play_id < 500, loc_x + runif(1, -2, 2), if_else(shot_desc == "Layup Shot" & play_id < 750, loc_x + runif(1, -2, 2), if_else(shot_desc == "Layup Shot", loc_x + runif(1, -2, 2), loc_x)))))

trice_shots_2020_test <- trice_shots_2020_test %>% mutate(loc_y = if_else(shot_desc == "Layup Shot" & play_id < 250, loc_y + runif(1, -1, 2), if_else(shot_desc == "Layup Shot" & play_id < 500, loc_y + runif(1, -1, 2), if_else(shot_desc == "Layup Shot" & play_id < 750, loc_y + runif(1, -1, 2), if_else(shot_desc == "Layup Shot", loc_y + runif(1, -1, 2), loc_y)))))
```


#### Shot Chart

```{r Trice's Shot Chart}
gamezoneR::base_court +
  geom_point(data = trice_shots_2020_test, aes(loc_x, loc_y, color = shot_outcome), alpha = 0.6) + geom_text(data = trice_quadrant_percentages, x = 27.75, y = 5.5, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 1, as.character(made),""))) + geom_text(data = trice_quadrant_percentages, x = 22, y = 15.5, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 2, as.character(made),""))) + geom_text(data = trice_quadrant_percentages, x = 28, y = 31, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 6, as.character(made),"")))  + geom_text(data = trice_quadrant_percentages, x = 6, y = 25, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 5, as.character(made),""))) + geom_text(data = trice_quadrant_percentages, x = 45, y = 24, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 7, as.character(made),""))) + geom_text(data = trice_quadrant_percentages, x = 12.5, y = 15, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 4, as.character(made),""))) + geom_text(data = trice_quadrant_percentages, x = 37.5, y = 15, fontface = "bold", color = trice_quadrant_percentages$color, size = 3, aes(label = ifelse(Quadrant == 5, as.character(made),""))) + theme(text=element_text(size=16,  family="Myanmar Text"), legend.spacing.x = grid::unit(0, 'cm'),  plot.title = element_text(face = "bold", hjust = 0.5, size = 25/.pt, margin = margin(0, 0, 5, 0)), legend.title = element_text(size = 20/.pt, face = "bold"), 
legend.text = element_text(size = 22/.pt), legend.margin = margin(0, 0, 0, 0),
legend.position = 'bottom', legend.box.margin = margin(-35, 0, 0, 0),  plot.margin = margin(5, 0, 5, 0)) + 
labs(title = "D'Mitrick Trice's Shot Chart: 2020-21 Season", color = "Outcome", caption = "Creator: @jonmichaelstroh | Data: @gamezoneR")
```